language: node_js
node_js:
  - "stable"
cache:
  dependencies:
    node_modules
script:
  - npm install
  - npm test
  - yarn build

deploy:
  provider: surge
  skip_cleanup: true
  domain: free1111-head.surge.sh
  project: ./build/

on: 
  branch: master